---

- name: install weechat packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - weechat
      - weechat-plugins
      - weechat-scripts
      - weechat-perl
      - weechat-lua
      - weechat-python
      - logrotate
      # for matrix plugin:
      - lua-cjson
      # for notifications:
      - libnotify-bin


- name: copy weechat files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
  become: yes
  become_user: "{{ normal_user }}"
