---

- name: install golang packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
    - golang


- name: copy golang files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
  become: yes
  become_user: "{{ normal_user }}"


- name: set GOPATH
  blockinfile:
    dest: "/home/{{ normal_user }}/.zshenv"
    block: |
            export GOPATH="{{ gopath }}"
    marker: "# {mark} go block"


- name: add GO bins to PATH
  lineinfile:
    dest: /home/vic/.zshenv
    line: 'PATH="$PATH:$HOME/code/go/bin"'
    insertafter: "# Construct path:"


- name: install go deps not packaged yet
  # deps that aren't packaged yet:
  shell: |
          # editor deps:
          export GOPATH="{{ gopath }}"
          go get -u github.com/nsf/gocode
          go get -u github.com/golang/lint/golint
          go get -u github.com/rogpeppe/godef
          go get -u golang.org/x/tools/cmd/guru
          go get -u golang.org/x/tools/cmd/gorename
          go get -u golang.org/x/tools/cmd/goimports
          go get -u golang.org/x/tools/cmd/godoc
          go get -u github.com/kisielk/errcheck
          go get -u github.com/mdempsky/unconvert
          go get -u github.com/alecthomas/gometalinter
          "{{ gopath }}"/bin/gometalinter --install --update
          go get -u github.com/derekparker/delve/cmd/dlv
          go get -u github.com/godoctor/godoctor
          go get -u github.com/fatih/gomodifytags
          go get -u github.com/zmb3/gogetdoc
          go get -u github.com/cweill/gotests/...
          go get -u github.com/haya14busa/gopkgs/cmd/gopkgs
          go get -u github.com/davidrjenni/reftools/cmd/fillstruct
          go get -u github.com/josharian/impl
          # grpc deps:
          go get -u google.golang.org/grpc
          go get -u github.com/golang/protobuf/protoc-gen-go
  become:  yes
  become_user: "{{ normal_user }}"
