---

- name: install golang packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - golang


- name: copy golang files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
  become: yes
  become_user: "{{ normal_user }}"


- name: set GOPATH
  blockinfile:
    dest: "/home/{{ normal_user }}/.zshenv"
    block: |
            export GOPATH="{{ gopath }}"
    marker: "# {mark} go block"


- name: add GO bins to PATH
  lineinfile:
    dest: /home/vic/.zshenv
    line: 'PATH="$PATH:$HOME/code/go/bin"'
    insertafter: "# Construct path:"


- name: install go deps not packaged yet
  command: go get -v {{ item }}
  environment:
    GOPATH: "{{ gopath }}"
  args:
    creates: "{{ gopath }}/src/{{ item }}"
  with_items:
    # grpc deps:
    - google.golang.org/grpc
    - github.com/golang/protobuf/protoc-gen-go
    # debugserver deps:
    - github.com/derekparker/delve/cmd/dlv
    # langserver deps:
    - golang.org/x/tools/cmd/gopls

  become:  yes
  become_user: "{{ normal_user }}"


