---

- name: install golang packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - golang


- name: copy golang files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
  become: yes
  become_user: "{{ normal_user }}"


- name: set GOPATH
  blockinfile:
    dest: "/home/{{ normal_user }}/.zshenv"
    block: |
            export GOPATH="{{ gopath }}"
    marker: "# {mark} go block"


- name: add GO bins to PATH
  lineinfile:
    dest: /home/vic/.zshenv
    line: 'PATH="$PATH:$HOME/code/go/bin"'
    insertafter: "# Construct path:"


- name: install go deps not packaged yet
  command: go get -v {{ item }}
  environment:
    GOPATH: "{{ gopath }}"
  args:
    creates: "{{ gopath }}/src/{{ item }}"
  with_items:
    # grpc deps:
    - google.golang.org/grpc
    - github.com/golang/protobuf/protoc-gen-go
    # debugserver deps:
    - github.com/derekparker/delve/cmd/dlv
    # langserver deps:
    - github.com/mdempsky/gocode
    - github.com/rogpeppe/godef
    - golang.org/x/tools/cmd/guru
    - golang.org/x/tools/cmd/gorename
    - golang.org/x/tools/cmd/goimports
    - github.com/zmb3/gogetdoc
    - github.com/cweill/gotests/...
    - github.com/haya14busa/gopkgs/cmd/gopkgs
    - github.com/davidrjenni/reftools/cmd/fillstruct
    - github.com/josharian/impl
    # optional linter aggregator
    - github.com/golangci/golangci-lint/cmd/golangci-lint
    - github.com/alecthomas/gometalinter
    # optional emacs:
    - github.com/godoctor/godoctor #refactoring
    - github.com/fatih/gomodifytags #edit field tags

  become:  yes
  become_user: "{{ normal_user }}"


- name: install gometalinter dependencies
  command: '"{{ gopath }}"/bin/gometalinter --install'
  environment:
    GOPATH: "{{ gopath }}"
  become:  yes
  become_user: "{{ normal_user }}"
  tags:
    - skip_ansible_lint
