---

dependencies:
  - role: server
    vars:
      apt_sources:
        - buster
  - role: softwareraid
    when: '"vagrant" in inventory_file'
  - smartd
  - cockpit
  - nfs-server
  - borgbackup-server
  - git-server
