---

dependencies:
  - bootstrap
  - { role: unattended, when: '"vagrant" in inventory_file' }
  - apt_sources
  - zsh
  - emacs
  - tmux
  - vim
  - yubikey
  - gnupg
  - git
  - debuggers
  - pass
  - weechat
  # - lxc
  - libvirt # FIXME python3-libvirt doesn't get imported correctly in ansible
  - vagrant
  - debian_devel
  - nvim
  - signing_party
  - virtualenvwrapper
  - beets
  - golang
  - vscode
  - private
  - docker
  - apparmor
  - rust

# TODO remove in ansible >= 2.10 when ansible-lint is not angry
galaxy_info:
  author: viccuad
  description: local
  license: "GPL3+"
  min_ansible_version: 2.9
  platforms:
  - name: Debian
    versions:
    - all
