---

dependencies:
  - bootstrap
  - { role: unattended, when: '"vagrant" in inventory_file' }
  - role: apt-sources
    sources:
      - buster
  - zsh
  - emacs
  - tmux
  - vim
  - gnupg
  - git
  - debuggers
  - pass
  - weechat
  - lxc
  - libvirt
  - vagrant
  - debian
  # - nvim
  - signing-party
  - virtualenvwrapper
  - beets
  - golang
  - vscode
  - { role: private, when: '"vagrant" not in inventory_file' }
  - docker
