---

dependencies:
  - bootstrap
  - { role: unattended, when: '"vagrant" in inventory_file' }
  - apt-sources
  - zsh
  - emacs
  - tmux
  - vim
  - gnupg
  - git
  - debuggers
  - pass
  - weechat
  - lxc
  - libvirt
  - vagrant
  - debian-devel
  - nvim
  - signing-party
  - virtualenvwrapper
  - beets
  - golang
  - vscode
  - { role: private, when: '"vagrant" not in inventory_file' }
  - docker
  - apparmor
