---

- name: install cockpit packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - cockpit
      # suggested packages:
      - cockpit-doc
      - cockpit-docker
      - cockpit-packagekit
      - cockpit-machines # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912725
      - cockpit-pcp


# - name: enable cockpit on firewalld internal zone
#   # TODO needs python-firewall for python2, not packaged
#   # https://github.com/ansible/ansible-modules-extras/issues/1282~
#   firewalld:
#     zone: internal
#     service: cockpit
#     permanent: true
#     state: enabled


- name: enable cockpit on firewalld internal zone
  command: firewall-cmd --permanent --add-service=cockpit --zone=internal
  register: out
  changed_when: '"Warning: ALREADY_ENABLED: cockpit" not in out.stderr'
  notify: reload firewalld
  # TODO missing python firewalld bindings, can't use firewalld ansible module yet
