---

- name: install cockpit packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - cockpit
      # suggested packages:
      - cockpit-doc
      - cockpit-packagekit
      - cockpit-machines # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912725
      - cockpit-pcp




- name: enable cockpit on firewalld internal zone
  firewalld:
    zone: internal
    service: cockpit
    permanent: true
    state: enabled
