---
ansible-lint:
  stage: test
  image: registry.gitlab.com/pipeline-components/ansible-lint:latest
  script:
    - ansible-lint --show-relpath all.yml

# disabled, needs privileged container for systemd
# test-idempotence-bootstrap:
#   script:
#     # patch to run against localhost
#     - "sed -i -- 's/- hosts: all/- hosts: localhost/g' bootstrap.yml"
#     # localhost must be explicitly on the inventory so inventory_file var is
#     # defined
#     - "sed -i -- '/[dotfiles]/a localhost' inventories/vagrant/hosts"
#     # needed for /etc/init.d/ssh
#     - mkdir -p /var/run/sshd

#     # Run the playbook
#     - ansible-playbook -i inventories/vagrant/hosts -vv bootstrap.yml

#     # Run the playbook again, checking to make sure it's idempotent
#     - >
#       ansible-playbook -i inventories/vagrant/hosts -vv bootstrap.yml
#       | grep -q 'changed=0.*failed=0'
#       && (echo 'Idempotence test: pass' && exit 0)
#       || (echo 'Idempotence test: fail' && exit 1)

# disabled, needs privileged container for systemd
# test-dotfiles-dryrun:
#   script:
#     # patch to run against localhost
#     - "sed -i -- 's/- hosts: dotfiles/- hosts: localhost/g' dotfiles.yml"

#     # Run the playbook
#     - "ansible-playbook -i inventories/vagrant/host -vv dotfiles.yml --check"
