---

- hosts: dotfiles
  become: yes
  roles:
    - bootstrap
    - { role: unattended, when: '"vagrant" in inventory_file' }
    - role: apt-sources
      sources:
        - buster
        - experimental
    - dotfiles
