---

- name: clone paper icon repo to tmp
  git:
    repo: https://github.com/snwh/paper-icon-theme.git
    dest: /tmp/paper-icon-theme
    update: no
  become: yes
  become_user: "{{ normal_user }}"


- name: install paper icon theme
  shell: |
          rm -rf /home/{{ normal_user }}/.icons/Paper*
          mkdir /home/{{ normal_user }}/.icons
          cp -rf /tmp/paper-icon-theme/Paper /home/{{ normal_user }}/.icons/
          cp -rf /tmp/paper-icon-theme/Paper-Mono-Dark /home/{{ normal_user }}/.icons/
          rm -rf /tmp/paper-icon-theme
  become: yes
  become_user: "{{ normal_user }}"
