---

- name: install gtk themes' deps packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - gnome-themes-standard
      - gtk2-engines
      - gtk2-engines-pixbuf
      - gtk2-engines-murrine
      - gtk2-engines-aurora


- name: clone materia repo to tmp
  git:
    repo: https://github.com/nana-4/materia-theme.git
    dest: /tmp/materia-theme
    update: no
  become: yes


- name: install materia theme
  shell: /tmp/materia-theme/install.sh
  become: yes


- name: change themes
  shell: |
          gsettings set org.gnome.desktop.interface gtk-theme "Flat-Plat-light-compact"
          gsettings set org.gnome.desktop.interface icon-theme 'Paper'
          gsettings set org.gnome.desktop.interface cursor-theme 'Paper'
  become: yes
  become_user: "{{ normal_user }}"


- name: install materia GDM theme
  # this needs a gtk theme previously selected:
  # https://github.com/nana-4/materia-theme/wiki/GDM-Theme
  shell: |
          GTK_THEME=$(gsettings get org.gnome.desktop.interface gtk-theme | sed "s/'//g")
          sudo cp -v --backup /usr/share{/themes/$GTK_THEME,}/gnome-shell/gnome-shell-theme.gresource
  become: yes
