---

- name: add backup server to main ssh_config (when production)
  blockinfile:
    dest: /etc/ssh/ssh_config
    block: |
      Host {{ backup_server_host }}
          User {{ backup_user }}
    marker: "# {mark} backup-client block"
  when: '"vagrant" not in inventory_file'


- name: add backup server to main ssh_config with no key checking (when vagrant)
  blockinfile:
    dest: /etc/ssh/ssh_config
    block: |
      Host {{ backup_server_host }}
          User {{ backup_user }}
          StrictHostKeyChecking no
          UserKnownHostsFile=/dev/null
    marker: "# {mark} backup-client block"
  when: '"vagrant" in inventory_file'


- name: add backup server ssh fingerprint to known hosts
  template:
    src: known_hosts
    dest: /etc/ssh/ssh_known_hosts
    owner: root
    group: root
    mode: 0644


- name: generate root's ssh key
  command: ssh-keygen -b 4096 -t rsa -f /root/.ssh/id_rsa -N '' -C "root@{{ inventory_hostname }}" -q
  args:
    creates: /root/.ssh/id_rsa


- name: install borgbackup
  apt:
    name: "{{ item }}"
    install_recommends: no
  with_items:
    - borgbackup
    - pwgen


- name: generate the backup password
  shell: |
    touch {{ backup_pwfile|quote }} && \
    chmod 0600 {{ backup_pwfile|quote }} && \
    pwgen -s -y -1 150 1 > {{ backup_pwfile|quote }} && \
    chmod 0400 {{ backup_pwfile|quote }} && \
    chattr +i {{ backup_pwfile|quote }}
  args:
    creates: "{{ backup_pwfile }}"
    warn: no


- name: be sure about backup_pwfile's permissions
  file:
    path: "{{ backup_pwfile }}"
    owner: root
    group: root
    mode: 0400
    attr: i


- name: install backup script
  template:
    src: run-backup.sh
    dest: /usr/local/sbin/run-backup
    owner: root
    group: root
    mode: 0755


- name: install the run-backup.service systemd unit
  template:
    src: "{{ item }}"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: 0644
  with_items:
    - run-backup.service
    - run-backup.timer
    - run-backup.slice


- name: enable the timer
  systemd:
    unit: run-backup.timer
    daemon_reload: yes
    enabled: yes
    state: started


# TODO ssh keys


- name: initialize the borgbackup repository for the first time
  command: run-backup init
  args:
    creates: /root/.config/borg/keys
  become: yes


# to test:
# date --set='+1 day'
# journalctl -f -u run-backup # with raid it takes a while
