---

- name: install game packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - minetest
      - retroarch
      # - zsnes
      - mednafen
      # - pcsx2


- name: check if i386 is enabled
  shell: dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1


- name: enable i386 architecture for steam
  command: dpkg --add-architecture i386
  when: result_i386_check.rc == 1


- name: save agreement to steam license
  debconf:
    name: steam
    question: steam/license
    value: ''
    vtype: select
  become: yes


- name: save agreement to steam question
  debconf:
    name: steam
    question: steam/question
    value: 'I AGREE'
    vtype: select
  become: yes


- name: install steam packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - steam
      - steam-devices


- name: copy steam files
  copy:
    src: steam
    dest: "/home/{{ normal_user }}/"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"
  become: yes
  become_user: "{{ normal_user }}"


- name: fix priority of udev configuration for steam controller
  # FIXME see https://github.com/ValveSoftware/steam-for-linux/issues/5169
  file:
    src: /lib/udev/rules.d/99-steam-controller-perms.rules
    dest: /lib/udev/rules.d/60-steam-controller-perms.rules
    state: link
    force: yes
    follow: false
  notify: reload udev rules


- name: patch udev configuration for steam controller
  # FIXME see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=818905
  lineinfile:
    path: /lib/udev/rules.d/99-steam-controller-perms.rules
    regexp: '^(KERNEL=="uinput")'
    line: 'KERNEL=="uinput", SUBSYSTEM=="misc", OPTIONS+="static_node=uinput", TAG+="uaccess"'
    state: present
    backrefs: yes
  notify: reload udev rules
