---

- name: install game packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - minetest
      - retroarch
      # - zsnes
      - mednafen
      # - pcsx2


- name: check if i386 is enabled
  shell: dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1


- name: enable i386 architecture for steam
  command: dpkg --add-architecture i386
  when: result_i386_check.rc == 1
  notify: update apt cache


- meta: flush_handlers


- name: save agreement to steam license
  debconf:
    name: steam
    question: steam/license
    value: ''
    vtype: select
  become: yes


- name: save agreement to steam question
  debconf:
    name: steam
    question: steam/question
    value: 'I AGREE'
    vtype: select
  become: yes


- name: install steam packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - steam
      - steam-devices


- name: copy steam files
  copy:
    src: steam
    dest: "/home/{{ normal_user }}/"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"
  become: yes
  become_user: "{{ normal_user }}"


# TODO add steam-streaming service to home zone when
# firewalld-0.6.0 ships the service file: https://github.com/firewalld/firewalld/blob/master/config/services/steam-streaming.xml
# firewall-cmd --zone=home --permanent --add-service=steam-streaming
# meanwhile, do it by hand:
- name: open firewalld for steam streaming
  command: firewall-cmd --zone=home --permanent --add-service=steam-streaming
  register: out
  changed_when: '"Warning: ALREADY_ENABLED: ssh" not in out.stderr'
  notify: reload firewalld
  # FIXME missing python firewalld bindings, can't use firewalld ansible module yet
