---

- name: install game packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - minetest
      - retroarch
      # - zsnes
      - mednafen
      # - pcsx2


- name: check if i386 is enabled
  command: dpkg --print-foreign-architectures | grep i386
  register: result_i386_check
  changed_when: result_i386_check.rc == 1
  failed_when: result_i386_check.rc > 1


- name: enable i386 architecture for steam
  command: dpkg --add-architecture i386
  when: result_i386_check.rc == 1


- name: save agreement to steam license
  debconf:
    name: steam
    question: steam/license
    value: ''
    vtype: select
  become: yes


- name: save agreement to steam question
  debconf:
    name: steam
    question: steam/question
    value: 'I AGREE'
    vtype: select
  become: yes


- name: install steam packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - steam
      - steam-devices


- name: copy steam files
  copy:
    src: steam
    dest: "/home/{{ normal_user }}/"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"
  become: yes
  become_user: "{{ normal_user }}"


- name: fix shipped udev configuration for steam controller
  file:
    src: /lib/udev/rules.d/99-steam-controller-perms.rules
    dest: /lib/udev/rules.d/60-steam-controller-perms.rules
    state: link
    force: yes
    follow: false
  notify: reload udev rules
