---

- name: install vagrant packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - vagrant
      - bridge-utils
      - vagrant-lxc
      - vagrant-libvirt
      - vagrant-sshfs


- name: set vagrant env vars
  blockinfile:
    dest: "/home/{{ normal_user }}/.zshenv"
    block: |
            export VAGRANT_DEFAULT_PROVIDER="libvirt"
            # export VAGRANT_LOG=INFO
    marker: "# {mark} vagrant block"
