---

- name: install freedombox packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
    - freedombox-setup


- name: exec freedombox-setup (if freedombox not installed yet)
  shell: '/usr/lib/freedombox/setup &> /var/log/freedombox-setup.log'
  args:
    creates: /var/log/freedombox-setup.log
  when: |
         ansible_distribution == 'Debian' and
         ansible_distribution_major_version == '9'




