---

# TODO from flatpak. Doesn't work, doesn't have access to PATH and shell
#
# - name: install vscode flatpak
#     flatpak install -y --from https://flathub.org/repo/appstream/com.visualstudio.code.flatpakref
#
#
# - name: add code alias
#   lineinfile:
#     dest: "/home/{{ normal_user }}/.zsh/aliases.zsh"
#     line: 'alias code="com.visualstudio.code --reuse-window"'
#
#
# - name: copy vscode files
#   copy:
#     src: .
#     dest: "/home/{{ normal_user }}/.var/app/com.visualstudio.code/config/Code/User/"
#     owner: "{{ normal_user }}"
#     group: "{{ normal_user }}"


- name: download the vscode tar
  get_url:
    url:  https://vscode-update.azurewebsites.net/latest/linux-x64/stable
    dest: /tmp/vscode.tar.gz
    mode: 0755


- name: extract vscode tar into ~/.apps/
  unarchive:
    src: /tmp/vscode.tar.gz
    dest: "/home/{{ normal_user }}/.apps/"
    remote_src: yes
    creates: "/home/{{ normal_user }}/.apps/VSCode-linux-x64"
  become: yes
  become_user: "{{ normal_user }}"


- name: symlink code in ~./local/bin
  file:
    src: "/home/{{ normal_user }}/.apps/VSCode-linux-x64/code"
    dest: "/home/{{ normal_user }}/.local/bin/code"
    state: link
  become: yes
  become_user: "{{ normal_user }}"


- name: install vscode dependencies
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - gvfs-bin # move to trash support
      - libgconf-2-4
      - libnotify4
      - libnss3
      - libxkbfile1
      - libsecret-1-0


- name: add code alias
  lineinfile:
    dest: "/home/{{ normal_user }}/.zsh/aliases.zsh"
    line: 'alias code="code --reuse-window --disable-gpu"'


- name: copy vscode files
  copy:
    src: .
    dest: "/home/{{ normal_user }}/"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"


- name: install vscode extensions
  shell: ~/.apps/VSCode-linux-x64/bin/code --install-extension "{{ item }}"
  args:
    creates: "/home/{{ normal_user }}/.vscode/extensions/{{ item }}*"
  with_items:
    - ms-vscode.go
    - vscodevim.vim
    - bazelbuild.vscode-bazel
    - redhat.vscode-yaml
    - ms-azuretools.vscode-docker
  become: yes
  become_user: "{{ normal_user }}"
    
