---

# Manually: DEBIAN_FRONTEND=noninteractive apt -y full-upgrade

- name: install server packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: no
  vars:
    items:
      - apt-listchanges
      - uptimed
      - unattended-upgrades
      - needrestart


- name: configure dpkg to retain old configs
  blockinfile:
    dest: /etc/dpkg/dpkg.cfg
    block: |
            force-confold
            force-confdef
    marker: "# {mark} unattended dist-upgrade block"


- name: configure apt-listchanges to send mails
  template:
    src: listchanges.conf
    dest: /etc/apt/listchanges.conf
    owner: root
    group: root
    mode: 0644


- name: configure unattended-upgrades
  template:
    src: "{{ item }}"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 20auto-upgrades
    - 50unattended-upgrades


- name: configure apt-listbugs
  template:
    src: "{{ item }}"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10apt-listbugs


- name: configure popularity-contest
  template:
    src: popularity-contest.conf
    dest: /etc/popularity-contest.conf
    owner: root
    group: root
    mode: 0644


- name: configure needrestart
  lineinfile:
    dest: /etc/needrestart/needrestart.conf
    regexp: '^#$nrconf{restart}'
    line: "$nrconf{restart} = 'a';"


- name: workaround needrestart bug #876459
  # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=876459
  template:
    src: workaround_needrestart
    dest: /etc/needrestart/conf.d/noninteractive.conf
    owner: root
    group: root
    mode: 0644


- name: configure uptimed to send emails
  lineinfile:
    dest: /etc/uptimed.conf
    regexp: '^SEND_EMAIL=\d'
    line: "SEND_EMAIL=1"
  notify: restart uptimed


- name: configure postfix to relay mail
  debconf:
    name: postfix
    question: postfix/relayhost
    value: '{{ mail_smarthost }}'
    vtype: select
  when: mail_smarthost != None
