---

host_key_checking: False
ansible_connection: ssh
ansible_user: vagrant
become_user: vagrant
deploy_user: vagrant
normal_user: vic

normal_user_name: John Doe
normal_user_email: john@doe.example
normal_user_gpgkey: E3C5114C0C5B4C49BA030991A2591E231E251F36
