---

- name: install beets packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
    - beets


- name: copy beets files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
      - "--perms"
  become: yes
  become_user: "{{ normal_user }}"
