---

- name: create .icons directory
  file:
    path: "/home/{{ normal_user }}/.icons"
    state: directory
  become: yes
  become_user: "{{ normal_user }}"


- name: clone paper icon repo to .icons
  git:
    repo: https://github.com/snwh/paper-icon-theme.git
    dest: "/home/{{ normal_user }}/.icons"
    update: yes
    version: master
  become: yes
  become_user: "{{ normal_user }}"
