---

- name: copy gnupg files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
      - "--perms"
      - "--chmod=u+rwx,g-rwx,o-rwx"
  become: yes
  become_user: "{{ normal_user }}"


- name: install gnupg packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - scdaemon
    - dirmngr
    - tor
    - hopenpgp-tools # check for problems in your key


- name: set env for gpg
  blockinfile:
    dest: "/home/{{ normal_user }}/.zshenv"
    block: |
            # From gpg-agent manual (for gpg 2.1)
            GPG_TTY=$(tty)
            export GPG_TTY
            # Tell ssh that we are using gpg-agent for ssh:
            unset SSH_AGENT_PID
            if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
                export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
            fi
    marker: "# {mark} gnupg block"






- name: import gpg public key
  shell: |
          gpg --recv-keys "{{ normal_user_gpgkey }}"
          echo "{{ normal_user_gpgkey }}:6:" | gpg --import-ownertrust
  become: yes
  become_user: "{{ normal_user }}"
