---

- import_tasks: nested_kvm.yml


- name: install libvirt packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon
      - libvirt-daemon-system
      - bridge-utils
      - dnsmasq-base
      - iptables
      - virt-top
      - virt-manager


- name: add {{ normal_user }} user to libvirt group
  user:
    name: "{{ normal_user }}"
    groups: "libvirt,libvirt-qemu"
    append: yes
  become: yes


- name: add libvirt env vars
  blockinfile:
    dest: '/home/{{ normal_user }}/.zshenv'
    block: |
            export LIBVIRT_DEFAULT_URI=qemu:///system
    marker: "# {mark} libvirt block"


- name: set nested_qemu fact
  command: systemd-detect-virt
  changed_when: false
  register: nested_qemu
  ignore_errors: yes


- name: define default libvirt network
  virt_net:
    command: define
    name: default
    xml: '{{ lookup("template", "default.xml.j2") }}'
    state: 'present'
  notify:
    - restart libvirtd
    - restart libvirt-guests


- name: do not check libvirt ssh host keys
  blockinfile:
    dest: '/home/{{ normal_user }}/.ssh/config'
    create: yes
    block: |
            Host *.libvirt
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
    marker: "# {mark} libvirt block"
  become: yes
  become_user: "{{ normal_user }}"


- name: be sure libvirtd is running and enabled
  service:
    name: libvirtd
    state: started
    enabled: yes


- name: install resolvconf
  apt:
    name: resolvconf
    state: present


- name: enable .libvirt DNS resolution for the host
  blockinfile:
    block: '{{ lookup("template", "tail.j2") }}'
    dest: /etc/resolvconf/resolv.conf.d/tail
  notify: rerun resolvconf
