---

- name: install debuggers packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - gdb
      - gdb-multiarch
      - rr
      # - ltrace # not in testing
      - strace
      - valgrind
      - tcpdump
      - net-tools
      - nmap
      - mitmproxy
      - mtr # traceroute substitute


- name: copy debuggers files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
  become: yes
  become_user: "{{ normal_user }}"
