---

- name: install non gui flatpak packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - flatpak


- name: add the flathub flatpak repository
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    method: user
  become: yes
  become_user: "{{ normal_user }}"


- name: add the winepak flatpak repository
  flatpak_remote:
    name: winepak
    state: present
    flatpakrepo_url: https://dl.winepak.org/repo/winepak.flatpakrepo
    method: user
  become: yes
  become_user: "{{ normal_user }}"


- name: install spotify
  flatpak:
    name: com.spotify.Client
    state: present
    remote: flathub
    method: user
  become: yes
  become_user: "{{ normal_user }}"


- name: install riot
  flatpak:
    name: im.riot.Riot
    state: present
    remote: flathub
    method: user
  become: yes
  become_user: "{{ normal_user }}"


- name: install slack
  flatpak:
    name: com.slack.Slack
    state: present
    remote: flathub
    method: user
  become: yes
  become_user: "{{ normal_user }}"


- name: add flatpak exports/bin to PATH
  # this poses no risk, see https://github.com/flatpak/flatpak/pull/1254
  lineinfile:
    dest: /home/vic/.zshenv
    line: 'PATH="$PATH:/var/lib/flatpak/exports/bin"'
    insertafter: "# Construct path:"
