---

- name: install non gui flatpak packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - flatpak


- name: add flathub repo
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  become: yes


- name: add flatpak exports/bin to PATH
  # this poses no risk, see https://github.com/flatpak/flatpak/pull/1254
  lineinfile:
    dest: /home/vic/.zshenv
    line: 'PATH=$PATH:/var/lib/flatpak/exports/bin'
    insertafter: "# Construct path:"
