---

- name: install zsh packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: no
  vars:
    items:
      - zsh
      - trash-cli
      - zsh-syntax-highlighting
      - autojump
      - git # for prompt
      - silversearcher-ag
      - dict
      - direnv


- name: copy zsh files
  copy:
    src: .
    dest: "/home/{{ normal_user }}/"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"


- name: copy zshrc template
  template:
    src: .zshrc.j2
    dest: "/home/{{ normal_user }}/.zshrc"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"


- name: set zsh as default shell of {{ normal_user }}
  user:
    name: "{{ normal_user }}"
    shell: /bin/zsh
  become: yes


- name: create ~/.apps directory
  file:
    path: "/home/{{ normal_user }}/.apps"
    state: directory
  become: yes
  become_user: "{{ normal_user }}"


- name: add ~/.local/bin to PATH
  lineinfile:
    dest: /home/vic/.zprofile
    line: 'export PATH="$PATH:$HOME/.local/bin"'
  become:  yes
  become_user: "{{ normal_user }}"
