---

- name: install lxc packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - lxc
      - bridge-utils


- name: set nested_container fact
  command: systemd-detect-virt
  changed_when: false
  register: nested_container
  ignore_errors: yes


- name: copy lxc-net config
  # https://wiki.debian.org/LXC/SimpleBridge#Using_lxc-net
  template:
    src: lxc-net.j2
    dest: /etc/default/lxc-net
    # owner: "{{ normal_user }}"
    # group: "{{ normal_user }}"
  notify: restart lxc-net


- name: copy lxc default.conf config
  # https://wiki.debian.org/LXC/SimpleBridge#Using_lxc-net
  template:
    src: default.conf.j2
    dest: /etc/lxc/default.conf
    # owner: "{{ normal_user }}"
    # group: "{{ normal_user }}"
  notify: restart lxc-net


- name: workaround, create ~/.ssh
  # TODO https://github.com/ansible/ansible/issues/20986
  file:
    path: ~/.ssh
    state: directory
  become: yes
  become_user: "{{ normal_user }}"


- name: do not check lxc ssh host keys
  blockinfile:
    dest: '/home/{{ normal_user }}/.ssh/config'
    create: yes
    block: |
            Host *.lxc
              StrictHostKeyChecking no
              UserKnownHostsFile=/dev/null
    marker: "# {mark} lxc block"
  become: yes
  become_user: "{{ normal_user }}"


- name: be sure lxc-net is running and enabled
  service:
    name: lxc-net
    state: started
    enabled: yes


- name: add lxc to sudoers.d
  # run lxc commands as root, preserving environment:
  lineinfile:
    dest: /etc/sudoers.d/lxc
    create: yes
    line: '{{ normal_user }}  ALL = NOPASSWD:SETENV: /usr/bin/lxc-*'
    validate: 'visudo -cf %s'


- name: give {{normal_user }} subuids for unprivileged containers
  lineinfile:
    path: /etc/subuid
    state: present
    regexp: "^{{ normal_user }}(.*?)$"
    line: '{{ normal_user }}:100000:65536'
    create: yes
  become: yes


- name: give {{normal_user }} subgids for unprivileged containers
  lineinfile:
    path: /etc/subgid
    state: present
    regexp: "^{{ normal_user }}(.*?)$"
    line: '{{ normal_user }}:100000:65536'
    create: yes
  become: yes


- name: workaround, create ~/.config/lxc
  # TODO https://github.com/ansible/ansible/issues/20986
  file:
    path: ~/.config/lxc
    state: directory
  become: yes
  become_user: "{{ normal_user }}"


- name: create ~/.config/lxc/default.conf for unprivileged containers
  copy:
    content: |
              lxc.include = /etc/lxc/default.conf
              lxc.idmap = u 0 100000 65536
              lxc.idmap = g 0 100000 65536
    dest: "/home/{{ normal_user }}/.config/lxc/default.conf"
  become: yes
  become_user: "{{ normal_user }}"


- name: create /etc/lxc/lxc-usernet for unprivileged containers
  copy:
    content: |
              # allow {{ normal_user }} to create up to 20 veth0
              # connected the lxcbr0:
              {{ normal_user }} veth lxcbr0 10
    dest: "/etc/lxc/lxc-usernet"
  become: yes


- name: check kernel supports LXC (ns & cgroups)
  command: lxc-checkconfig
  become: yes
  changed_when: false


- name: enable "unprivileged_userns_clone" sysctl know between restarts
  copy:
    content: |
              # thins the security https://lwn.net/Articles/673597/
              kernel.unprivileged_userns_clone=1
    dest: /etc/sysctl.d/80-lxc-userns.conf
  become: yes
  notify: reload sysctl rules
