---

- name: install laptop-related packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - tlp
      - tp-smapi-dkms
      - acpi-call-dkms
      - anacron


- name: install laptop-related packages from non-free
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - firmware-iwlwifi


- name: add alias for charge-batteries-totally
  lineinfile:
    dest: "/home/{{ normal_user }}/.zsh/aliases.zsh"
    line: 'alias charge-batteries-totally="sudo tlp fullcharge BAT0; sudo tlp fullcharge BAT1"'


- name: enable mac spoofing for wifi and ethernet
  # See https://blogs.gnome.org/thaller/2016/08/26/mac-address-spoofing-in-networkmanager-1-4-0
  blockinfile:
    dest: /etc/NetworkManager/conf.d/30-mac-randomization.conf
    create: yes
    block: |
            [device-mac-randomization]
            # "yes" is already the default for scanning
            wifi.scan-rand-mac-address=yes

            [connection-mac-randomization]
            ethernet.cloned-mac-address=random
            wifi.cloned-mac-address=random
    marker: "# {mark} ansible block"
    mode: 0644
    owner: root
    group: root


- name: copy tlp config
  copy:
    src: tlp
    dest: /etc/tlp.conf
    mode: 0644
    owner: root
    group: root
  notify: restart tlp
