---

- name: install pass packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - pass
      - suckless-tools
      - xdotool


- name: add pass alias
  lineinfile:
    dest: "/home/{{ normal_user }}/.zsh/aliases.zsh"
    line: "alias passmenu='/usr/share/doc/pass/examples/dmenu/passmenu --type'"
