---

- name: install gui packages from main
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - python-psutil # for dconf
      - anacron
      # - emacs25-lucid # gui
      - task-gnome-desktop
      - dconf-gsettings-backend
      - fwupd
      - gnome-software-plugin-flatpak
      - xdg-desktop-portal-gtk
      - firefox-esr
      - webext-https-everywhere
      - webext-ublock-origin
      - thunderbird
      - enigmail
      - dconf-gsettings-backend
      - dconf-editor
      - libcanberra-gtk-module
      - network-manager-ssh-gnome
      - network-manager-openvpn-gnome
      - firewall-applet
      - bluez-obexd
      - calibre
      - ardour
      - chromium
      - drumgizmo
      - dgedit
      - guitarix
      - gparted
      - meld
      - git-gui
      - gnome-shell-pomodoro
      - gnome-shell-extension-caffeine
      - gnome-shell-extension-impatience
      - gnome-shell-extension-system-monitor
      - gnome-shell-extension-suspend-button
      - gnome-shell-extension-top-icons-plus
      - torbrowser-launcher
      - gnome-mpv
      - vlc
      - virt-manager
      - gnome-shell-extensions
      - vrms
      - pinentry-gnome3
      # - yubioath-desktop # TODO
      - yubikey-personalization
      - yubikey-personalization-gui
      - intel-gpu-tools
      - revolt
      - libratbag-tools
      - gnome-nettool


- name: make sure some gui packages are not present
  apt:
    name: "{{ items }}"
    state: absent
  vars:
    items:
      - iceweasel
      - icedove


- name: install packages from contrib/nonfree
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - unrar
      - intel-microcode
      - iucode-tool


- name: set gnome settings with dconf
  # export settings with:
  # gsettings list-recursively | grep -i org.gnome.desktop | sort | uniq > gsettings_export
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: "{{ dconfsettings }}"
  become: yes
  become_user: "{{ normal_user }}"


- name: create gnome keybindings for passmenu
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: "{{ passmenusettings }}"
  become: yes
  become_user: "{{ normal_user }}"


- name: create ~/Templates folder
  file:
    path: "/home/{{ normal_user }}/Templates"
    state: directory
    mode: 0755
  become: yes
  become_user: "{{ normal_user }}"


- name: create "Empty document" template in ~/Templates
  copy:
    content: ""
    dest: "/home/{{ normal_user }}/Templates/Empty document"
    force: no
  become: yes
  become_user: "{{ normal_user }}"


# TODO workaround https://github.com/ansible/ansible/issues/42384
- name: mask unwanted gnome services
  file:
    src: /dev/null
    dest: /home/{{ normal_user }}/.config/systemd/user/{{ item }}
    state: link
    force: yes
  with_items:
    - tracker-store.service
    - gvfs-goa-volume-monitor.service # gnome online accounts support
  become: yes
  become_user: "{{ normal_user }}"


- name: remove tracker databases
  file:
    name: ~/.cache/tracker
    state: absent
  become: yes
  become_user: "{{ normal_user }}"


- name: install gtk/gdm themes
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - materia-gtk-theme
