---

- name: install gui packages from main
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
    - python-psutil # for dconf
    - anacron
    - emacs25-lucid # gui
    - task-gnome-desktop
    - dconf-gsettings-backend
    - fwupd
    - gnome-software-plugin-flatpak
    - xdg-desktop-portal-gtk
      # - xul-ext-ublock-origin # TODO
    - xul-ext-https-everywhere
    - xul-ext-itsalltext
    - xul-ext-noscript
    - dconf-gsettings-backend
    - dconf-editor
    - libcanberra-gtk-module
    - network-manager-ssh-gnome
    - network-manager-openvpn-gnome
    - firewall-applet
    - bluez-obexd
    - calibre
    - ardour
    - chromium
    - drumgizmo
    - dgedit
    - guitarix
    - gparted
    - meld
    - git-gui
    - gnome-shell-pomodoro
    - gnome-shell-extension-caffeine
    - gnome-shell-extension-impatience
    - gnome-shell-extension-system-monitor
    - gnome-shell-extension-suspend-button
    - gnome-shell-extension-top-icons-plus
    - torbrowser-launcher
    - gnome-mpv
    - vlc
    - virt-manager
    - gnome-shell-extensions
    - vrms
    - pinentry-gnome3
    # - yubioath-desktop # TODO
    - yubikey-personalization
    - yubikey-personalization-gui
    - intel-gpu-tools
    - revolt
    - firefox # from experimental


- name: make sure some gui packages are not present
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - firefox-esr
    - icedove


- name: install packages from contrib/nonfree
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - unrar
      - intel-microcode
      - iucode-tool


- name: install flathubs
  shell: |
         flatpak install -y --from https://flathub.org/repo/appstream/com.spotify.Client.flatpakref
  register: out
  ignore_errors: yes
  failed_when: '"is already installed" not in out.stderr'
  become: yes
  become_user: "{{ normal_user }}"


- name: set gnome settings with dconf
  # export settings with:
  # gsettings list-recursively | grep -i org.gnome.desktop | sort | uniq > gsettings_export
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: "{{ dconfsettings }}"
  become: yes
  become_user: "{{ normal_user }}"


- name: create gnome keybindings for passmenu
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  with_items: "{{ passmenusettings }}"
  become: yes
  become_user: "{{ normal_user }}"


- name: create "Empty document" template in ~/Templates
  copy:
    content: ""
    dest: "/home/{{ normal_user }}/Templates/Empty document"
    force: no
  become: yes
  become_user: "{{ normal_user }}"


- name: mask unwanted gnome services
  systemd:
    name: "{{item}}"
    user: yes
    masked: yes
    state: stopped
  loop:
    - gvfs-goa-volume-monitor.service
    - tracker-store.service
  become: yes
  become_user: "{{ normal_user }}"


- name: remove tracker databases
  file:
    name: ~/.cache/tracker
    state: absent
  become: yes
  become_user: "{{ normal_user }}"


- name: install gtk/gdm themes
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
      - materia-gtk-theme
