---

- name: install git packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - git
      - git-email
      - tig


- name: copy git files
  copy:
    src: .
    dest: "/home/{{ normal_user }}/"
    mode: 0644
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"


- name: copy git config
  template:
    src: .gitconfig.j2
    dest: "/home/{{ normal_user }}/.gitconfig"
    mode: 0644
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"
