- name: update apt cache if needed and autoremove packages
  apt:
    update_cache: yes
    cache_valid_time: 3600
    autoremove: yes


- name: reload udev rules
  shell: 'udevadm control --reload-rules && udevadm trigger'


- name: reload firewalld
  service:
    name: firewalld
    state: restarted
