---

- name: install emacs packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - emacs-nox # non-gui
      - emacs-common-non-dfsg # not in main
      - xclip
      - aspell
      - aspell-en
      - aspell-de
      - aspell-es
      - gnutls-bin # for emacs 26.1 workaround, see https://github.com/syl20bnr/spacemacs/commit/427c01c27a20e065ff1e58ab9173103cec377e0c
      - python3-proselint
      # markdown layer:
      - markdown
      # git layer:
      - git-flow
      # c/c++ layer:
      - gcc
      - cppcheck
      - clang
      - ccls
      - global # for ggtags (helm-ggtags):
      - exuberant-ctags
      - pkg-config
      # shell layer:
      - shellcheck
      - python3-bashate
      # python layer:
      # python-language-server # Missing in Debian
      # latex layer:
      - pandoc
      # protobuf layer:
      - protobuf-compiler
      # doom.d:
      - fd-find
      - ripgrep


- name: copy emacs files
  copy:
    src: .
    dest: "/home/{{ normal_user }}/"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"
    mode: 0644


- name: clone .spacemacs.d
  git:
    repo: https://gitlab.com/viccuad/spacemacs.d.git
    dest: "/home/{{ normal_user }}/.spacemacs.d/"
    update: no
    version: master
  become: yes
  become_user: "{{ normal_user }}"


- name: clone spacemacs' .emacs.d
  git:
    repo: https://github.com/syl20bnr/spacemacs.git
    dest: "/home/{{ normal_user }}/.emacs.d.spacemacs/"
    update: no
    version: develop
  become: yes
  become_user: "{{ normal_user }}"


- name: clone doom's .emacs.d
  git:
    repo: https://github.com/hlissner/doom-emacs.git
    dest: "/home/{{ normal_user }}/.emacs.d/"
    # dest: "/home/{{ normal_user }}/.emacs.d.doom/"
    depth: 1
    update: no
    version: master
  become: yes
  become_user: "{{ normal_user }}"


- name: clone .doom.d
  git:
    repo: https://gitlab.com/viccuad/doom.d.git
    dest: "/home/{{ normal_user }}/.doom.d/"
    update: no
    version: master
  become: yes
  become_user: "{{ normal_user }}"


- name: initialize doom emacs
  command: "/home/{{ normal_user }}/.emacs.d/bin/doom -y install"
  args:
    creates: "/home/{{ normal_user }}/.emacs.d/.local"
  become:  yes
  become_user: "{{ normal_user }}"

# - name: change EDITOR to emacsclient
#   replace:
#     dest: "/home/{{ normal_user }}/.zshenv"
#     regexp: 'EDITOR=(.*|$)'
#     replace: 'EDITOR="emacsclient -t"'

# - name: add emacs ALTERNATE_EDITOR=""
#   lineinfile:
#     dest: "/home/{{ normal_user }}/.zshenv"
#     line: 'export ALTERNATE_EDITOR=""'
#     insertafter: "EDITOR=(.*|$)"

- name: add emacs aliases
  blockinfile:
    dest: '/home/{{ normal_user }}/.zsh/aliases.zsh'
    block: |
            alias e="emacsclient -t -c"
            alias magit='emacsclient -t -c -e "(progn (magit-status) (delete-other-windows))"'
    marker: "# {mark} emacs block"
