---

- name: install emacs packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
    - emacs25-nox # non-gui
    - emacs25-common-non-dfsg # not in main
    - emacs-goodies-el
    - xclip
    - aspell
    - aspell-en
    - aspell-de
    - aspell-es
    - python3-proselint
    # markdown layer:
    - markdown
    # c/c++ layer:
    - gcc
    - cppcheck
    - cscope
    - clang
    - clang-format
    - clang-tidy
    - global # for ggtags (helm-ggtags):
    - exuberant-ctags
    - pkg-config
    # shell layer:
    - shellcheck
    - python3-bashate
    # python layer:
      # - flake8 using pylint instead, because it is broken for now TODO
    - pylint
    - pylint3
    - python3-pylint-*
    - python-jedi
    - python3-jedi
    - python-hacking
    - python3-hacking
    - hy
    - yapf
    - yapf3
    # - autoflake missing in Debian TODO
    # latex layer:
    - pandoc


- name: copy emacs files
  copy:
    src: .
    dest: "/home/{{ normal_user }}/"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"


- name: clone .emacs.d
  git:
    repo: https://github.com/syl20bnr/spacemacs.git
    dest: "/home/{{ normal_user }}/.emacs.d/"
    update: no
  become: yes
  become_user: "{{ normal_user }}"


- name: change EDITOR to emacsclient
  replace:
    dest: "/home/{{ normal_user }}/.zshenv"
    regexp: 'EDITOR=(.*|$)'
    replace: 'EDITOR="emacsclient -t"'


- name: add emacs ALTERNATE_EDITOR=""
  lineinfile:
    dest: "/home/{{ normal_user }}/.zshenv"
    line: 'export ALTERNATE_EDITOR=""'


- name: add emacsclient alias
  lineinfile:
    dest: "/home/{{ normal_user }}/.zsh/aliases.zsh"
    line: 'alias e="emacsclient -t -c"'
