---

- name: install pass packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
    - signing-party


- name: copy .caffrc config
  template:
    src: .caffrc.j2
    dest: "/home/{{ normal_user }}/.caffrc"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"

- name: copy caff files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
      - "--perms"
      - "--chmod=u+rwx,g-rwx,o-rwx"
