---

- name: install tmux packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - tmux
      - ncurses-term # for the tmux-256color terminfo
      - xsel


- name: copy tmux files
  copy:
    src: .
    dest: "/home/{{ normal_user }}/"
    owner: "{{ normal_user }}"
    group: "{{ normal_user }}"
    mode: 0644
