---

# TODO
# To enable docker memory limitation, the kernel needs to be loaded with
# boot parameters: cgroup_enable=memory swapaccount=1.
# This adds runtime overhead.
# See: /usr/share/doc/docker.io/README.Debian


- name: install docker packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: no
  vars:
    items:
      - docker.io
      # - docker-compose # https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=918012


- name: add {{ normal_user }} to docker group
  user:
    name: "{{ normal_user }}"
    groups: docker
    append: yes
  become: yes


- name: enable swapaccount
  lineinfile:
    state: present
    dest: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=\"(?!.*cgroup_enable=memory swapaccount=1).*)(\")'
    line: '\1 cgroup_enable=memory swapaccount=1\2'
    backrefs: true
  notify: update grub
