---

# TODO
# To enable docker memory limitation, the kernel needs to be loaded with
# boot parameters: cgroup_enable=memory swapaccount=1.
# This adds runtime overhead.
# See: /usr/share/doc/docker.io/README.Debian


- name: install docker packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: no
  with_items:
    - docker.io
    - docker-compose


- name: add {{ normal_user }} to docker group
  user:
    name: "{{ normal_user }}"
    groups: docker
    append: yes
  become: yes
