---

dependencies:
  - bootstrap
  - apt_sources
  - zsh
  - emacs
  - tmux
  - vim
  - gnupg
  - git
  - pass
  - signing_party

# TODO remove in ansible >= 2.10 when ansible-lint is not angry
galaxy_info:
  author: viccuad
  description: local
  license: "GPL3+"
  min_ansible_version: 2.9
  platforms:
  - name: Debian
    versions:
    - all
