---

- name: restart libvirtd
  service:
    name: libvirtd
    state: restarted


- name: restart libvirt-guests
  service:
    name: libvirt-guests
    state: restarted


- name: rerun resolvconf
  shell: |
          resolvconf --enable-updates
          resolvconf -u


- name: reload kvm-intel kernel module
  shell: |
    rmmod kvm-intel
    modprobe kvm-intel


- name: reload kvm-amd kernel module
  shell: |
    rmmod kvm-amd
    modprobe kvm-amd
