---

- name: restart libvirtd
  service:
    name: libvirtd
    state: restarted


- name: restart libvirt-guests
  service:
    name: libvirt-guests
    state: restarted


- name: rerun resolvconf
  shell: |
          resolvconf --enable-updates
          resolvconf -u
