---

- hosts: all
  become: yes
  roles:
    - common
  pre_tasks:
    - name: update apt cache if needed and autoremove packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        autoremove: yes


- hosts: workstation
  become: yes
  roles:
    - workstation


- hosts: dotfiles
  become: yes
  roles:
    - dotfiles
