---

- name: bootstrap
  hosts: all
  become: yes
  roles:
    - bootstrap
  pre_tasks:
    - name: update apt cache if needed and autoremove packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        autoremove: yes


- hosts: workstation
  become: yes
  roles:
    - testing-repos


- name: dotfiles
  hosts: dotfiles
  become: yes
  roles:
    - zsh
    - emacs
    - tmux
    - vim
    - gnupg
    - git
    - pass
    - weechat
    - lxc
    - vagrant
    - debian
    # - nvim
    - signing-party
    - virtualenvwrapper
    - beets
    - golang
