---

- name: install pcengines packages
  apt:
    name: "{{ item }}"
    state: present
    install_recommends: yes
  with_items:
    - lm-sensors
    - flashrom


- name: configure grub to show output during boot
  lineinfile:
    dest: /etc/default/grub
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=', line: 'GRUB_CMDLINE_LINUX_DEFAULT="console=tty0 console=ttyS0,115200n8"' }
    - { regexp: '^GRUB_TERMINAL=', line: 'GRUB_TERMINAL=serial' }
    - { regexp: '^GRUB_SERIAL_COMMAND=', line: 'GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"' }
  notify: update grub
