---
- name: install nvim packages
  apt:
    name: "{{ items }}"
    state: present
    install_recommends: yes
  vars:
    items:
      - neovim
      - wl-clipboard
      - nodejs # for mason plugin
      # optional deps:
      # nerd-fonts
      - luarocks
      - gdu

- name: copy nvim files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
  become: yes
  become_user: "{{ normal_user }}"

- name: set nvim env vars
  blockinfile:
    dest: "/home/{{ normal_user }}/.zshenv"
    block: |
      export NVIM_TUI_ENABLE_TRUE_COLOR=1
    marker: "# {mark} nvim block"

- name: add nvim aliases
  blockinfile:
    dest: "/home/{{ normal_user }}/.zsh/aliases.zsh"
    block: |
      alias nv="nvim"
    marker: "# {mark} nvim block"

- name: change EDITOR to nvim
  replace:
    dest: "/home/{{ normal_user }}/.zshenv"
    regexp: "EDITOR=(.*|$)"
    replace: 'EDITOR="nvim"'
