---

- name: copy font files
  synchronize:
    src: .
    dest: "/home/{{ normal_user }}/"
    perms: yes
    recursive: yes
    links: yes
    rsync_opts:
      - "--exclude=.git*"
      - "--perms"
      - "--chmod=u+rwx,g-rwx,o-rwx"
  become: yes
  become_user: "{{ normal_user }}"


- name: reload font cache
  shell: fc-cache -f
  become: yes
